apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-exporter
  namespace: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-exporter
  template:
    metadata:
      labels:
        app: mongo-exporter
    spec:
      containers:
        - name: mongo-exporter
          image: bitnami/mongodb-exporter:latest
          ports:
            - containerPort: 9216
              name: mongo-exporter
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
