apiVersion: batch/v1
kind: CronJob
metadata:
  name: haproxy-log-exporter
  namespace: prometheus
spec:
  schedule: "0 */12 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: export-haproxy-logs
            image: public.ecr.aws/aws-cli/aws-cli:latest
            command:
              - /bin/sh
              - -c
              - |
                yum install -y zip gzip jq && \
                /opt/export/export-haproxy-logs-to-s3.sh
            volumeMounts:
              - name: script-volume
                mountPath: /opt/export
            env:
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: aws-creds
                    key: access_key
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: aws-creds
                    key: secret_key
              - name: AWS_DEFAULT_REGION
                value: me-south-1
          restartPolicy: OnFailure
          volumes:
            - name: script-volume
              configMap:
                name: haproxy-export-configmap
                defaultMode: 0755
