# frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: prometheus
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: mirmika/restauranty-deployment-frontend:${IMAGE_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: frontend-secret
---
apiVersion: v1
kind: Service
metadata:
  name: restauranty-deployment-frontend-1
  namespace: prometheus
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000 
  type: ClusterIP
