---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy
  namespace: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
      - name: haproxy
        image: haproxy:latest
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: haproxy-config
          mountPath: /usr/local/etc/haproxy/haproxy.cfg
          subPath: haproxy.cfg
        ports:
        - containerPort: 80
      volumes:
      - name: haproxy-config
        configMap:
          name: haproxy-config
---
apiVersion: v1
kind: Service
metadata:
  name: haproxy-service
  namespace: prometheus
  labels:
    app: haproxy
spec:
  selector:
    app: haproxy
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: metrics
      port: 8404
      targetPort: 8404
  type: LoadBalancer
