---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy
  namespace: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
      - name: haproxy
        image: haproxy:latest
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: haproxy-config
          mountPath: /usr/local/etc/haproxy/haproxy.cfg
          subPath: haproxy.cfg
        - name: haproxy-tls
          mountPath: /etc/ssl/private/haproxy.pem
          subPath: haproxy.pem
        ports:
         - containerPort: 80
         - containerPort: 443
         - containerPort: 8404  # Expose metrics port
      volumes:
      - name: haproxy-config
        configMap:
          name: haproxy-config
      - name: haproxy-tls
        secret:
          secretName: haproxy-tls

---
apiVersion: v1
kind: Service
metadata:
  name: haproxy-service
  namespace: prometheus
  labels:
    app: haproxy
spec:
  selector:
    app: haproxy
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443  
    - name: stats
      port: 8404
      targetPort: 8404  # Expose metrics port  
  type: LoadBalancer
