apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy
  namespace: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
      - name: haproxy
        image: haproxy:latest
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: haproxy-config
          mountPath: /usr/local/etc/haproxy/haproxy.cfg
          subPath: haproxy.cfg
        - name: haproxy-tls
          mountPath: /etc/ssl/private/haproxy.pem
          subPath: haproxy.pem
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 8404
      volumes:
      - name: haproxy-config
        configMap:
          name: haproxy-config
      - name: haproxy-tls
        secret:
          secretName: haproxy-tls
